config/routes.rb
Rails.application.routes.draw do
  get 'connection/index'

  get 'connection/create'

  get 'connection/destroy'

  resources :tags
  get 'tag/:tag', to: 'users#index', as: :tag_user

  resources :conversations do
      resources :messages
  end

  resources :connections

  devise_for :users, :path => 'u', controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations',
    confirmations: 'users/confirmations'
  }
  get 'static/home'
  resources :users, except: [:new, :create]


  get '/info', to: 'users#info', as: :info_path

  get '/blogs', to: 'users#blogs', as: :blog_path

  authenticated :user do
    # root :to => 'static#home', as: :authenticated_root
    root :to => 'users#info', as: :authenticated_root

  end
  root :to => 'static#home'
end

app/views/layouts/_header.html.erb
<header id="header">
  <%= link_to image_tag("logo2.png"), users_path, class: 'logo' %>
  <ul class="icons">
    <% if user_signed_in? %>
        <% if current_user.role == "student"  %>
          <li><%= link_to "Profile",  user_path(current_user), class: "logo" %></li>
          <li><%= link_to "Mentors",  conversations_path, class: "logo" %></li>
        <% elsif current_user.role == "mentor"  %>
          <li><%= link_to "Find",  root_path, class: "logo" %></li>
          <li><%= link_to "Profile",  user_path(current_user), class: "logo" %></li>
          <li><%= link_to "Mentees",  conversations_path, class: "logo" %></li>
        <% end %>
      <% if current_user.admin %>
        <li><%= link_to "Tags",  tags_path, class: "logo" %></li>
      <% end %>
      <li><%= link_to "Logout", destroy_user_session_path, method: :delete, class: "logo" %></li>
    <% else %>
      <li><%= link_to "Login", new_user_session_path, class: "logo" %></li>
      <li><%= link_to "Sign Up", new_user_registration_path, class: "logo" %></li>
    <% end %>
  </ul>
</header>

<!-- <header id="header">



                <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                    <ul class="icons">
                      <% if user_signed_in? %>
                          <% if current_user.role == "student"  %>
                            <li><%= link_to "Find",  root_path, class: "logo" %></li>
                            <li><%= link_to "Profile",  user_path(current_user), class: "logo" %></li>
                            <li><%= link_to "Mentors",  conversations_path, class: "logo" %></li>
                          <% elsif current_user.role == "mentor"  %>
                            <li><%= link_to "Find",  root_path, class: "logo" %></li>
                            <li><%= link_to "Profile",  user_path(current_user), class: "logo" %></li>
                            <li><%= link_to "Mentees",  conversations_path, class: "logo" %></li>
                          <% end %>
                        <% if current_user.admin %>
                          <li><%= link_to "Tags",  tags_path, class: "logo" %></li>
                        <% end %>
                        <li><%= link_to "Logout", destroy_user_session_path, method: :delete, class: "logo" %></li>
                      <% else %>
                        <li><%= link_to "Login", new_user_session_path, class: "logo" %></li>
                        <li><%= link_to "Sign Up", new_user_registration_path, class: "logo" %></li>
                      <% end %>
                    </ul>
                </div


     </header> -->

app/views/layouts/_messages.html.erb
<% flash.each do |key, value| %>
  <div class="alert alert-<%= key %>">
    <a href="#" data-dismiss="alert" class="close">×</a>
    <ul>
      <li>
        <%= value %>
      </li>
    </ul>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Coffeealum</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

  </head>

  <body>

        <div id="wrapper">

            <div id="main">
                <%= render 'layouts/header' %>
              <div class="container-fluid">
                  <%= render 'layouts/messages' %>

                    <%= yield %>
              </div>
            </div>
        </div>

    

  </body>
</html>